@echo off
set ANTHROPIC_BASE_URL=https://api.deepseek.com/anthropic
set ANTHROPIC_API_KEY=YOUR_DEEPSEEK_API_KEY_HERE
set ANTHROPIC_MODEL=deepseek-v4-pro
set CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
claude
